version: "3"

# To connect other containers to cloudflare tunnel create a shared network
networks:
  cloudflared:

services: 
  cloudflared: 
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: "tunnel --no-autoupdate run" 
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TUNNEL_TOKEN=MY_AMAZING_TOKEN
    networks:
      - cloudflared
