version: '3'

networks:
  proxy:
    external: true

services:
  statping:
    container_name: statping
    image: adamboutcher/statping-ng:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Paris
      PUID: 1000
      PGID: 1000
      DB_CONN: sqlite
    volumes:
      - ./app:/app
#    ports:
#      - 8080:8080
    networks:
      - proxy
