version: '3'

networks:
  proxy:
    external: true
  ghost:

services:
  ghost:
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment: 
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      NODE_ENV: production 
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ghostusr
      database__connection__password: PASSWORD_DB
      database__connection__database: ghost
      mail__transport: SMTP
      mail__options__service: SMTP
      mail__from: ghost@domain.tld
      mail__options__host: mail.domain.tld
      mail__options__port: 587
      mail__options__auth__user: user
      mail__options__auth__pass: password
      url: https://blog.domain.tld
    volumes:
      - ./app:/var/lib/ghost/content
    networks:
      - ghost
      - proxy

  # To publish ghost blog directly add this to ghost
  #    ports:
  #      - 80:2368

  ghost-db:
    image: mariadb:latest
    container_name: ghost-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
       - ./db:/var/lib/mysql:z  # Persist storage
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      # Beware of special characters in password that can be interpreted by shell
      MYSQL_ROOT_PASSWORD: PASSWORD_ROOT
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghostusr
      MYSQL_PASSWORD: PASSWORD_DB
    networks:
      - ghost

